trailingComma: "es5"
tabWidth: 2
semi: true
singleQuote: true
printWidth: 80
arrowParens: always
bracketSpacing: true
htmlWhitespaceSensitivity: css
insertPragma: false
jsxSingleQuote: false
bracketSameLine: false
proseWrap: always
quoteProps: as-needed
requirePragma: false
useTabs: false
